import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { roomId, files } = await req.json();

    if (!roomId || !files) {
      return NextResponse.json({ error: "Missing roomId or files" }, { status: 400 });
    }

    // Check for GitHub token
    const githubToken = process.env.GITHUB_TOKEN;
    if (!githubToken) {
      return NextResponse.json(
        { error: "GitHub token not configured. Set GITHUB_TOKEN in .env.local" },
        { status: 400 }
      );
    }

    // Use GitHub API to create/update files
    const owner = process.env.GITHUB_OWNER || "karthikeyagoud045-ANU";
    const repo = `vibe-room-${roomId}`;
    const branch = "main";

    // Try to get the repo, create if it doesn't exist
    let repoExists = false;
    const repoCheck = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github.v3+json",
      },
    });
    if (repoCheck.ok) {
      repoExists = true;
    } else {
      // Create repo
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: repo,
          description: `Generated by Ultimate Vibe Coder - Room ${roomId}`,
          private: false,
          auto_init: true,
        }),
      });
      if (!createRes.ok) {
        const err = await createRes.json();
        return NextResponse.json(
          { error: `Failed to create repo: ${err.message}` },
          { status: 400 }
        );
      }
    }

    // Get the latest commit SHA
    const refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${branch}`,
      {
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
        },
      }
    );

    let latestSha: string | undefined;
    if (refRes.ok) {
      const refData = await refRes.json();
      latestSha = refData.object.sha;
    }

    // Create blobs for each file
    const treeItems = [];
    for (const [path, content] of Object.entries(files)) {
      const blobRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/blobs`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${githubToken}`,
            Accept: "application/vnd.github.v3+json",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            content: Buffer.from(content as string).toString("base64"),
            encoding: "base64",
          }),
        }
      );
      if (!blobRes.ok) continue;
      const blobData = await blobRes.json();
      treeItems.push({ path, mode: "100644", type: "blob", sha: blobData.sha });
    }

    if (treeItems.length === 0) {
      return NextResponse.json({ error: "No files to push" }, { status: 400 });
    }

    // Create tree
    const treeRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/trees`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ tree: treeItems, base_tree: latestSha }),
      }
    );

    if (!treeRes.ok) {
      return NextResponse.json({ error: "Failed to create tree" }, { status: 400 });
    }
    const treeData = await treeRes.json();

    // Create commit
    const commitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/commits`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: `AI generation update - ${new Date().toISOString()}`,
          tree: treeData.sha,
          parents: latestSha ? [latestSha] : [],
        }),
      }
    );

    if (!commitRes.ok) {
      return NextResponse.json({ error: "Failed to create commit" }, { status: 400 });
    }
    const commitData = await commitRes.json();

    // Update ref
    await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`,
      {
        method: "PATCH",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ sha: commitData.sha }),
      }
    );

    return NextResponse.json({
      message: `Pushed ${treeItems.length} files to GitHub!`,
      repoUrl: `https://github.com/${owner}/${repo}`,
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Push failed" },
      { status: 500 }
    );
  }
}
